//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerMatching
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnswerMatching()
        {
            this.AnswerMatchingResult = new HashSet<AnswerMatchingResult>();
        }
    
        public int AnswerMatchingID { get; set; }
        public string LeftParth { get; set; }
        public string RightParth { get; set; }
        public int QuestionID { get; set; }


        [JsonIgnore]
        public virtual Question Question { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerMatchingResult> AnswerMatchingResult { get; set; }
    }
}
