//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerOrderResult
    {
        public int AnswerOrderResultID { get; set; }
        public int SelectedSerialNumber { get; set; }
        public int AnswerOrderID { get; set; }
        public int QuestionResultID { get; set; }
    
        public virtual AnswerOrder AnswerOrder { get; set; }
        public virtual QuestionResult QuestionResult { get; set; }
    }
}
