//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerMatchingResult
    {
        public int AnswerMatchingResultID { get; set; }
        public string SelectedLeftParth { get; set; }
        public string SelectedRightParth { get; set; }
        public int QuestionResultID { get; set; }
        public int AnswerMatchingID { get; set; }
    
        public virtual AnswerMatching AnswerMatching { get; set; }
        public virtual QuestionResult QuestionResult { get; set; }
    }
}
