//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomAnswer
    {
        public int CustomAnswerID { get; set; }
        public int QuestionResultID { get; set; }
        public string Body { get; set; }
        public Nullable<double> Grade { get; set; }
    
        public virtual QuestionResult QuestionResult { get; set; }
    }
}
