//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GraduateWorkEntities : DbContext
    {
        public GraduateWorkEntities()
            : base("name=GraduateWorkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answer { get; set; }
        public virtual DbSet<AnswerMatching> AnswerMatching { get; set; }
        public virtual DbSet<AnswerMatchingResult> AnswerMatchingResult { get; set; }
        public virtual DbSet<AnswerOrder> AnswerOrder { get; set; }
        public virtual DbSet<AnswerOrderResult> AnswerOrderResult { get; set; }
        public virtual DbSet<AnswerResult> AnswerResult { get; set; }
        public virtual DbSet<AnswerType> AnswerType { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<CustomAnswer> CustomAnswer { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<GroupSubject> GroupSubject { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Pupil> Pupil { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<QuestionResult> QuestionResult { get; set; }
        public virtual DbSet<Result> Result { get; set; }
        public virtual DbSet<SectionBlock> SectionBlock { get; set; }
        public virtual DbSet<SectionBlockResult> SectionBlockResult { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<SubjectCourse> SubjectCourse { get; set; }
        public virtual DbSet<SubjectCourseAvailable> SubjectCourseAvailable { get; set; }
        public virtual DbSet<SubjectSection> SubjectSection { get; set; }
        public virtual DbSet<SubjectSectionResult> SubjectSectionResult { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<TeacherSubjects> TeacherSubjects { get; set; }
        public virtual DbSet<Term> Term { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<TestAvailable> TestAvailable { get; set; }
        public virtual DbSet<TestType> TestType { get; set; }
        public virtual DbSet<Theory> Theory { get; set; }
    }
}
