//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectCourseAvailable
    {
        public int SubjectCourseID { get; set; }
        public int GroupID { get; set; }
        public bool SubjectCourseAvailable1 { get; set; }
        public int SubjectCourseAvailableID { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual SubjectCourse SubjectCourse { get; set; }
    }
}
