//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectSection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubjectSection()
        {
            this.SectionBlock = new HashSet<SectionBlock>();
            this.SubjectSectionResult = new HashSet<SubjectSectionResult>();
        }
    
        public int SubjectSectionID { get; set; }
        public string Name { get; set; }
        public string image { get; set; }
        public int SubjectCourseID { get; set; }
        public int HierarchyLevel { get; set; }
    
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectionBlock> SectionBlock { get; set; }
        [JsonIgnore]
        public virtual SubjectCourse SubjectCourse { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectSectionResult> SubjectSectionResult { get; set; }
    }
}
