//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectSectionResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubjectSectionResult()
        {
            this.SectionBlockResult = new HashSet<SectionBlockResult>();
        }
    
        public int SubjectSectionResultID { get; set; }
        public int SubjectSectionID { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public int PersonID { get; set; }
    
        public virtual Pupil Pupil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectionBlockResult> SectionBlockResult { get; set; }
        public virtual SubjectSection SubjectSection { get; set; }
    }
}
