//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public int TermID { get; set; }
        public int TheoryID { get; set; }
        public string Name { get; set; }
        public string Definition { get; set; }
    
        public virtual Theory Theory { get; set; }
    }
}
