//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class Theory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Theory()
        {
            this.Term = new HashSet<Term>();
        }
    
        public int QuestionID { get; set; }
        public string Body { get; set; }
        public int SectionBlockID { get; set; }
        public int Position { get; set; }
    
        [JsonIgnore]
        public virtual Question Question { get; set; }
        [JsonIgnore]
        public virtual SectionBlock SectionBlock { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Term> Term { get; set; }
    }
}
